# Pin assignments for b[3:0]
set_property PACKAGE_PIN W5 [get_ports {b[0]}]
set_property PACKAGE_PIN V6 [get_ports {b[1]}]
set_property PACKAGE_PIN AB5 [get_ports {b[2]}]
set_property PACKAGE_PIN AA6 [get_ports {b[3]}]

# I/O standard assignments for b[3:0]
set_property IOSTANDARD LVCMOS33 [get_ports {b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[3]}]

# Pin assignments for a[3:0]
set_property PACKAGE_PIN AB3 [get_ports {a[0]}]
set_property PACKAGE_PIN AB4 [get_ports {a[1]}]
set_property PACKAGE_PIN Y4 [get_ports {a[2]}]
set_property PACKAGE_PIN Y5 [get_ports {a[3]}]

# I/O standard assignments for a[3:0]
set_property IOSTANDARD LVCMOS33  [get_ports {a[0]}]
set_property IOSTANDARD LVCMOS33  [get_ports {a[1]}]
set_property IOSTANDARD LVCMOS33  [get_ports {a[2]}]
set_property IOSTANDARD LVCMOS33  [get_ports {a[3]}]

# Pin assignments for y[3:0]
set_property PACKAGE_PIN U5 [get_ports {y[0]}]
set_property PACKAGE_PIN V1 [get_ports {y[1]}]
set_property PACKAGE_PIN V4 [get_ports {y[2]}]
set_property PACKAGE_PIN V5 [get_ports {y[3]}]

# I/O standard assignments for y[3:0]
set_property IOSTANDARD LVCMOS33 [get_ports {y[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y[2]}]
set_property IOSTANDARD LVCMOS33  [get_ports {y[3]}]
